# packages in environment at /home/ubuntu/miniconda3/envs/bigdata:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10  
anyio                     2.2.0            py39h06a4308_1  
argon2-cffi               20.1.0           py39h27cfd23_1  
arviz                     0.11.2             pyhd3eb1b0_0  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.2.0             pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
blas                      1.0                         mkl  
bleach                    4.0.0              pyhd3eb1b0_0  
bottleneck                1.3.2            py39hdd57654_1  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.14.6           py39h400218f_0  
cftime                    1.5.1.1          py39hce1f21e_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cmdstanpy                 0.9.68                   pypi_0    pypi
conda-pack                0.6.0              pyhd3eb1b0_0  
convertdate               2.3.2                    pypi_0    pypi
cryptography              36.0.0           py39h9ce1e76_0  
curl                      7.80.0               h7f8727e_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.26                  pypi_0    pypi
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.0              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.3              py39h06a4308_0  
ephem                     4.1.3                    pypi_0    pypi
fonttools                 4.28.5                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
giflib                    5.2.1                h7b6447c_0  
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0               h553295d_15  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.6               hb1b8bf9_0  
hijri-converter           2.2.2                    pypi_0    pypi
holidays                  0.12                     pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.8.2            py39h06a4308_0  
importlib_metadata        4.8.2                hd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.4.1            py39h06a4308_1  
ipython                   7.29.0           py39hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.18.0           py39h06a4308_1  
jinja2                    3.0.2              pyhd3eb1b0_0  
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter_client            7.1.0              pyhd3eb1b0_0  
jupyter_core              4.9.1            py39h06a4308_0  
jupyter_server            1.4.1            py39h06a4308_0  
jupyterlab                3.2.1              pyhd3eb1b0_1  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.2             pyhd3eb1b0_0  
kernel-headers_linux-64   3.10.0              h57e8cba_10  
kiwisolver                1.3.2                    pypi_0    pypi
korean-lunar-calendar     0.2.1                    pypi_0    pypi
krb5                      1.19.2               hac12032_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.80.0               h0b77cf5_0  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-devel_linux-64     9.3.0               hb95220a_17  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libnetcdf                 4.6.1                h2053bdc_4  
libnghttp2                1.46.0               hce63b2e_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
lunarcalendar             0.0.9                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-base           3.5.0            py39h3ed280b_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
munkres                   1.1.4                      py_0  
nbclassic                 0.2.6              pyhd3eb1b0_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.3.0            py39h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
netcdf4                   1.5.7            py39he70f4c8_0  
notebook                  6.4.6            py39h06a4308_0  
numexpr                   2.8.1            py39h6abb31d_0  
numpy                     1.22.0                   pypi_0    pypi
numpy-base                1.21.2           py39h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
openssl                   1.1.1m               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.4.3            py39h06a4308_1  
parso                     0.8.3              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.0                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0  
plotly                    5.5.0                    pypi_0    pypi
prometheus_client         0.12.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prophet                   1.0.1                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
py4j                      0.10.9.2                 pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.10.0             pyhd3eb1b0_0  
pymeeus                   0.5.11                   pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyrsistent                0.18.0           py39heee7806_0  
pysocks                   1.7.1            py39h06a4308_0  
pyspark                   3.2.0                    pypi_0    pypi
pystan                    2.19.1.1         py39ha9443f7_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2021.3             pyhd3eb1b0_0  
pyzmq                     22.3.0           py39h295c915_2  
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd3eb1b0_0  
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3            py39hc147768_0  
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                58.0.4           py39h06a4308_0  
setuptools-git            1.2                      pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
sniffio                   1.2.0            py39h06a4308_1  
sqlite                    3.37.0               hc218d9a_0  
sysroot_linux-64          2.17                h57e8cba_10  
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.9.4            py39h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
ujson                     5.1.0                    pypi_0    pypi
urllib3                   1.26.7             pyhd3eb1b0_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
wheel                     0.37.0             pyhd3eb1b0_1  
xarray                    0.20.1             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.6.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0  
